@baseUrl = https://sushi-royal-api.azurewebsites.net
# @baseUrl = http://localhost:3000
### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"unknown",
    "password":"admin"
}

### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}


### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### GET
GET {{baseUrl}}/users

### POST
POST {{baseUrl}}/users/add
Content-Type: application/json

{
    "nom": "Julien",
    "prenom": "Remmery",
    "adresse": "test",
    "email": "test6@gmail.com",
    "mdp": "test"
}

### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "email":"test6@gmail.com",
    "password":"test"
}