GET http://localhost:3000/boxes

### Read all sushis
@baseUrl = http://localhost:3000

###Create box 
POST {{baseUrl}}/boxes/creationBox
Content-Type: application/json

{
    "box":[ {"idSushi":2, "quantity":1}, 
    {"idSushi":9, "quantity":2}]
}
